### ISSUE TITLE
Comprehensive TODO List

### ISSUE THREAD

**Issue by abhabongse** [abhabongse/questionsdb-firebase#1]
## Todo:

- [ ] Add additional data to each problem: **Author**, **Notes**, **Uploaded Images**
- [ ] Media query for printing (on another page)

## Done:

- [x] Add **snackbars** to sign-in, sign-out, and data changes
- [x] Add forwarding ref to `EditableMarkdown` (see: https://reactjs.org/docs/forwarding-refs.html)
- [x] New **account page**
- [x] Separate **routing** logic from component files
- [x] Change from `Object.keys(o)` to **`Object.entries(o)`** whenever makes sense
- [x] Add **separate page** for a single (editable) problem statement
- [x] Add **proper routing** on problem card ID click
- [x] Fix `forwardRef` to be compatible with `innerRef` https://material-ui.com/customization/css-in-js/#api
- [x] Drawer menu should have **active items** styling
- [x] For **ProblemItemPage**, add button to go back (or make a breadcrumb)
- [x] Problem ID should use fixed-width text box
- [ ] **Local storage** ~~should have timestamp so that the old one does not override the new one (in case that more than one tab~~ 
    - [x] Use `setInterval` to regularly pull state updates from local storage (10 sec)
- [x] **Import and export** page as JSON
- [x] Add **tagging** to each problem
    - **Rounds:** `audition`, `regional`, `final`
    - **Regions:** `north`, `northeast`, `central`, `south`
    - **Formats:** `multiple-choices`, `quickfire`, `pondering`, `coding``mathematics`, etc.~~
- [x] Add **date time** sorting (keep track of created time)
- [x] Create **global managers** for **dialog popups** and **snackbars** so that its lifecycle does not totally depend on the life of the logically attached components.
    - [ ] Introduce CSS transitions for components which relies dialogs and snackbars.
- [x] Make each problem in the list page **in-line editable**
- [x] Add **content filtering** on `ProblemsPage`
- [x] Horizontal scrolling when code overflow
- [x] Customize pseudocode syntax highlighting
- [x] Add KaTeX to allow Math mode typing (may need manual escape HTML before passing down)
- [x] **Reduce dizziness** with https://www.npmjs.com/package/react-scroll-to-component
- [ ] ~~Refactor code:~~
    - [ ] ~~Revisit **getter** and **setter** for each field value of `Problem`~~
    - [ ] ~~Clear confusion: things that is initialized once could/should be moved to `constructor` instead of the beginning of `render` method.~~
    - [ ] ~~Functionality of MobX `Problem` class should correspond with `ProblemCard`~~
    - [ ] ~~`ProblemStore` could be a separate file & `ProblemsContext` should be renamed to `ProblemStoreContext~~
- [x] `ProblemCardEdit` may no longer need to **observe**.
- [ ] ~~Add the **most recent update time** for each problem, and do not allow old problems to replace new ones~~ (superceded by the use of Firebase)
- [x] **Data synchronization** with Firebase ~~(how to sync with MobX?)~~
- [x] Move call to message snackbar to global location / disable click away
- [x] Remove all traces of "problems"
- [x] Toolbar for adding question / filtering results
    - [x] 3 standard fields + archived / deleted / normal
- [x] **Image uploading** with Firebase (use data URI for now)
